name: main
on: push

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: ["^1.13.1"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: |
          make build

      - name: Lint
        uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: "."
